import {Routes} from '@angular/router';
import {Home} from './home/home';
import {EditSingleChoiceField} from './edit/edit-single-choice-field/edit-single-choice-field.component';
import {EditFieldGroup} from './edit/edit-field-group/edit-field-group.component';
import {EditField} from './edit/edit-field/edit-field.component';
import {EditForm} from './edit/edit-form/edit-form.component';
import {EditFieldType} from './edit/edit-field-type/edit-field-type.component';
import {EditGroup} from './edit/edit-group/edit-group.component';
import {ListFieldTypes} from './list/list-field-types/list-field-types';
import {ListFields} from './list/list-fields/list-fields.component';
import {ListSingleChoiceFields} from './list/list-single-choice-fields/list-single-choice-fields';
import {ListFieldGroups} from './list/list-field-groups/list-field-groups';
import {ListForms} from './list/list-forms/list-forms';
import {ListGroups} from './list/list-groups/list-groups';
import {FieldTypeDetails} from './details/field-type-details/field-type-details';
import {FieldDetails} from './details/field-details/field-details';
import {SingleChoiceFieldDetails} from './details/single-choice-field-details/single-choice-field-details';
import {FieldGroupDetails} from './details/field-group-details/field-group-details';
import {FormDetails} from './details/form-details/form-details';
import {GroupDetails} from './details/group-details/group-details';

export const routes: Routes = [
  {path: 'home', component: Home},
  {path: 'list-field-types', component: ListFieldTypes},
  {path: 'list-fields', component: ListFields},
  {path: 'list-single-choice-fields', component: ListSingleChoiceFields},
  {path: 'list-field-groups', component: ListFieldGroups},
  {path: 'list-forms', component: ListForms},
  {path: 'list-groups', component: ListGroups},
  {path: 'edit-field-type', component: EditFieldType},
  {path: 'edit-field', component: EditField},
  {path: 'edit-single-choice-field', component: EditSingleChoiceField},
  {path: 'edit-field-group', component: EditFieldGroup},
  {path: 'edit-form', component: EditForm},
  {path: 'edit-group', component: EditGroup},
  {path: 'edit-field-type/:id', component: EditFieldType},
  {path: 'edit-field/:id', component: EditField},
  {path: 'edit-single-choice-field/:id', component: EditSingleChoiceField},
  {path: 'edit-field-group/:id', component: EditFieldGroup},
  {path: 'edit-form/:id', component: EditForm},
  {path: 'edit-group/:id', component: EditGroup},
  {path: 'field-type-details/:id', component: FieldTypeDetails},
  {path: 'field-details/:id', component: FieldDetails},
  {path: 'single-choice-field-details/:id', component: SingleChoiceFieldDetails},
  {path: 'field-group-details/:id', component: FieldGroupDetails},
  {path: 'form-details/:id', component: FormDetails},
  {path: 'group-details/:id', component: GroupDetails},
  {path: '**', redirectTo: 'home'}
];
